sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install -r requirements-py3.txt; else pip install -r requirements-py2.txt; fi
  - pip install coveralls
before_script:
  - psql -U postgres -c 'CREATE DATABASE dummy_test'
script:
  - nosetests --with-coverage --cover-package=csvkit
after_success:
  coveralls
