name: CI
on: [push, pull_request]
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11', pypy-3.7]
        exclude:
          - os: windows-latest
            python-version: 3.7
          - os: windows-latest
            python-version: pypy-3.7
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.py
      - run: pip install .[test] coveralls
      - env:
          LANG: en_US.UTF-8
          PYTHONIOENCODING: utf-8
          PYTHONUTF8: 1
        run: pytest --cov csvkit
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
